# https://pre-commit.com/#pre-commit-run
#exclude: '^(?:front/.*|back/api.*|back/schemas/.*)'
files: '^mte_website/.*py$' # https://regex101.com/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/hhatto/autopep8
    rev: main
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
    -   id: autoflake
-   repo: https://github.com/PyCQA/docformatter
    rev: release/v1.6.0
    hooks:
      - id: docformatter
-   repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
-   repo: local
    hooks:
    -   id: flakeheaven
        name: flakeheaven
        description: flakeheaven
        entry: flakeheaven lint
        language: python
        verbose: true
        types: [ python ]

    -   id: django-check
        name: django-check
        descirption: run django manage.py check
        entry: /Users/guntho/Library/Caches/pypoetry/virtualenvs/mte-django-2tBdu-fU-py3.10/bin/python mte_website/manage.py check
        language: script
        types: [ python ]
        pass_filenames: false
        always_run: true

