# Generated by Django 4.1.3 on 2023-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annuaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
